version: "3.8"

services:

  db:
    image: postgres
    environment:
      POSTGRES_DB: nest_starter
      POSTGRES_USER: nest_starter
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  admin:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  data:
